name: run-tests

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/run-tests.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.1]
        laravel: [^10.0]

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, redis
          coverage: none

      - name: Create database
        run: |
            sudo /etc/init.d/mysql start
            mysql  -u root -proot -e 'CREATE DATABASE IF NOT EXISTS mailcoach_tests;'

      - name: Set Laravel version
        run: |
            sed -i 's/^10.0/${{ matrix.laravel }}/g' composer.json

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        env:
          COMPOSER_ROOT_VERSION: dev-main
        with:
          composer-options: "--prefer-dist --no-interaction"

      - name: Execute tests
        run: composer test
        env:
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
          DB_PASSWORD: root
